"""changed enrollment_date type

Revision ID: 05f9e046ebc9
Revises: f30c36c2e7c0
Create Date: 2024-11-20 22:17:25.841987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '05f9e046ebc9'
down_revision: Union[str, None] = 'f30c36c2e7c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enrollment', 'enrollment_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enrollment', 'enrollment_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
